name: Beta SideStore Build

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+' # example: 1.0.0-beta.1

jobs:
  build:
    name: Build and Upload SideStore Beta
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: brew install ldid

      - name: Change version to tag
        run: sed -i '' -e "s/MARKETING_VERSION = .*/MARKETING_VERSION = ${{ github.ref_name }}/" Build.xcconfig

      - name: Get version
        id: version
        run: echo "::set-output name=version::$(grep MARKETING_VERSION Build.xcconfig | sed -e 's/MARKETING_VERSION = //g')"

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: '14.2'

      - name: Build SideStore
        run: |
          set -eo pipefail
          make build | xcpretty
          exit ${PIPESTATUS[0]}

      - name: Fakesign app
        run: make fakesign

      - name: Convert to IPA
        run: make ipa

      - name: Generate Changelog
        id: changelog
        run: |
          # Replace with your changelog generation script or tool
          echo "- Implemented feature XYZ" >> changelog.txt
          echo "- Fixed bug ABC" >> changelog.txt
          echo "::set-output name=changelog::$(cat changelog.txt)"

      - name: Upload to new beta release
        id: upload-release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref_name }}
          draft: true
          prerelease: true
          files: SideStore.ipa
          body: |
            <!-- NOTE: to reset SideSource cache, go to `https://apps.sidestore.io/reset-cache/nightly/<sidesource key>`. This is not included in the GitHub Action since it makes draft releases so they can be edited and have a changelog. -->
            Beta builds are hand-picked builds from development commits that will allow you to try out new features earlier than normal. However, **they might contain bugs and other issues. Use at your own risk!**

            ## Changelog
            ${{ steps.changelog.outputs.changelog }}

            ## Build Info
            Built at (UTC): $(date -u +'%c')
            Built at (UTC date): $(date -u +'%Y-%m-%d')
            Commit SHA: ${{ github.sha }}
            Version: ${{ steps.version.outputs.version }}

      - name: Add version to IPA file name
        run: mv SideStore.ipa SideStore-${{ steps.version.outputs.version }}.ipa

      - name: Upload SideStore.ipa Artifact
        uses: actions/upload-artifact@v3
        with:
          name: SideStore-${{ steps.version.outputs.version }}.ipa
          path: SideStore-${{ steps.version.outputs.version }}.ipa

      - name: Upload *.dSYM Artifact
        uses: actions/upload-artifact@v3
        with:
          name: SideStore-${{ steps.version.outputs.version }}-dSYM
          path: ./*.dSYM/
